### ISSUE TITLE
License

### ISSUE THREAD

**Issue by onitake** [vsg-dev/osg2vsg#53]
What license terms is osg2vsg being released under?

There is no explicit license file and no indication in the source files.

**Comment by vsg-dev** [comment]
Thanks for the note, it's an oversight. It's MIT like the rest of the VSG.  I've added the LICENSE.md.

If you link to the osg2vsg library you'll also need to link to the OSG as well, which has the OSGPL (a slight relaxation of the LGPL).

**Comment by onitake** [comment]
Thanks!
