### ISSUE TITLE
structure "TBuiltInResource"  changed 

### ISSUE THREAD

**Issue by wadivision** [vsg-dev/osg2vsg#57]
I got a compile error after updating  vulkanSDK (1.2.141.0).
I found  **struct TBuiltInResource** that in  `$VulkanSDK\include\glslang\Include\ResourceLimits.h` change.

``` c++
struct TBuiltInResource {
   ...
    int maxMeshViewCountNV;

    int maxDualSourceDrawBuffersEXT; // a new member variable

    TLimits limits;

   ...
```

**Comment by robertosfield** [comment]
On Tue, 9 Jun 2020 at 13:19, wadivision <notifications@github.com> wrote:

> I got a compile error after updating vulkanSDK (1.2.141.0).
> I found *struct TBuiltInResource* that in
> $VulkanSDK\include\glslang\Include\ResourceLimits.h change.
>
> struct TBuiltInResource {
>    ...
>     int maxTaskWorkGroupSizeZ_NV;
>
>     int maxMeshViewCountNV; // a new member variable
>
>     TLimits limits;
>
>
>
Thanks for the note.  I'll pulled down 1.2.141.0 and work out how best to
tackle this issue.

**Comment by robertosfield** [comment]
glslang is a bit tortuous but I eventually figured out a way of allowing build against the VulkanSDK 1.2.141.0 and retain the build against ollder SDK's.  I have also applied this fix to vsgXchange.

https://github.com/vsg-dev/osg2vsg/commit/b6ab6da541a3271f2331b33fdb7c5a83a064b577
