### ISSUE TITLE
applications/vsgwithosg/vsgwithosg.cpp does not compile on Windows (Visual Studio)

### ISSUE THREAD

**Issue by PaulObermeier** [vsg-dev/osg2vsg#65]
The following lines in osg2vsg/applications/vsgwithosg/vsgwithosg.cpp
show similar errors as issue https://github.com/vsg-dev/vsgXchange/issues/99 using VisualStudio:
```
Line 232: auto osg_scene = osgDB::readRefNodeFile(filename);
Line 324: else osg_viewer.setCameraManipulator(new osgGA::AnimationPathManipulator(pathFilename));
```

Variables `filename` and `pathFilename` must have a `.string()` appended.

**Comment by robertosfield** [comment]
Thanks for the testing. Could you post PR's with these mods. I'm struggling with a broken arm so can't easily work so any help is appreciated.

**Comment by robertosfield** [comment]
I have merged the suggestions, hopefully this will resolve the Windows build: 503fba3b4a5e88ed839fcdfcd9f7e554532f9586
