### ISSUE TITLE
Missing up to date tag for building stable releases

### ISSUE THREAD

**Issue by rhabacker** [vsg-dev/osg2vsg#76]
To build stable binary packages on Linux (openSUSE) from this project, a tag is required which matches the current vsg API. The current [osg2vsg-0.0.0](https://github.com/vsg-dev/osg2vsg/releases/tag/osg2vsg-0.0.0) does not match the current vsg API.

**Comment by robertosfield** [comment]
And.... osg2vsg is along way from being ready for a stable release, no point making a stag till it's ready.  I'm close this PR as it's so premature.
